In [1]:
import os
import pandas as pd
import numpy as np
import json
import pickle
import argparse

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy.stats import ttest_1samp, ttest_ind, ttest_rel, permutation_test
from scipy.spatial.distance import pdist, squareform
from sklearn.decomposition import PCA
from statsmodels.stats import multitest
from matplotlib.backends.backend_pdf import PdfPages

from tfsemb_class import tsne, save_pickle, add_speech
from tfsplt_encoding import get_cmap_smap, aggregate_data, organize_data, get_elecbrain
from tfsplt_utils import read_folder, load_pickle, get_con_color
from tfsplt_brainmap import get_sigelecs, Colorbar, make_brainmap
from tfsplt_brainmap_cat import make_brainmap_cat

def fdr(pvals):
    _, pcor, _, _ = multitest.multipletests(
        pvals, method="fdr_bh", is_sorted=False
    )
    return pcor

### Load Data

In [3]:
class Args(argparse.Namespace):
  sid = ["777"] # subjects
  project = "podcast"
  formats = [ # encoding folder
    "../data/encoding/podcast/20240208-rephael/kw-podcast-full-777-glove50-lag2k-25-all-rephael1/*/*%s.csv",
    "../data/encoding/podcast/20240208-rephael/kw-podcast-full-777-glove50-lag2k-25-all-rephael2/*/*%s.csv",
  ]
  labels = [
    "aggregate",
    "control",
  ]
  sig_elec_file = ["../data/plotting/sig-elecs/podcast_160.csv"]
  keys = ["comp"] # comprehension and/or production
  lags_plot = np.arange(-2000,2001,25) # encoding lags
  lags_show = np.arange(-2000,2001,25) # lags for the effect
  lc_by = "labels"
  ls_by = "keys"

# Aggregate Data
args = Args()
args.unique_labels = list(dict.fromkeys(args.labels))
args.unique_keys = list(dict.fromkeys(args.keys))
args.lags_show = args.lags_show / 1000
args.lags_plot = args.lags_plot / 1000
args = get_sigelecs(args)  # get significant electrodes

df = aggregate_data(args) # aggregate data
df = organize_data(args, df) # trim data if necessary
df

Aggregating data

                                   0         1         2         3    \
label     electrode key  sid
aggregate 763_G34   comp 777  0.000980  0.001336  0.002659  0.010641
          717_LGB71 comp 777  0.093908  0.094129  0.099867  0.103620
          798_G87   comp 777  0.088249  0.090593  0.094587  0.100774
          742_G54   comp 777 -0.010553 -0.009936 -0.011776 -0.011627
          717_LGA32 comp 777 -0.009871 -0.000145  0.014530  0.021487
...                                ...       ...       ...       ...
control   763_G32   comp 777  0.025591  0.031791  0.031916  0.027069
          798_AIT3  comp 777  0.073384  0.068620  0.059497  0.044098
          798_G27   comp 777  0.028355  0.024463  0.020920  0.023100
          798_G84   comp 777  0.009439  0.014034  0.015819  0.014239
          742_G102  comp 777  0.049758  0.047470  0.046322  0.043966

                                   4         5         6         7    \
label     electrode key  sid
aggregate 763_G34   comp 777  0.019509  0.021723  0.025180  0.031295
          717_LGB71 comp 777  0.111857  0.114492  0.120157  0.128181
          798_G87   comp 777  0.103142  0.104010  0.102907  0.102473
          742_G54   comp 777 -0.009202 -0.011403 -0.016472 -0.017997
          717_LGA32 comp 777  0.020341  0.017467  0.012641  0.008572
...                                ...       ...       ...       ...
control   763_G32   comp 777  0.024121  0.018223  0.016849  0.023361
          798_AIT3  comp 777  0.030089  0.027063  0.027008  0.023320
          798_G27   comp 777  0.023123  0.017228  0.015705  0.022176
          798_G84   comp 777  0.014068  0.015365  0.020121  0.022541
          742_G102  comp 777  0.038675  0.033392  0.031406  0.037514

                                   8         9    ...       151       152  \
label     electrode key  sid                      ...
aggregate 763_G34   comp 777  0.037198  0.037403  ...  0.020532  0.011182
          717_LGB71 comp 777  0.133325  0.134320  ...  0.087753  0.089788
          798_G87   comp 777  0.103648  0.100996  ...  0.079841  0.070603
          742_G54   comp 777 -0.013121 -0.006504  ... -0.033988 -0.039896
          717_LGA32 comp 777 -0.001892 -0.011649  ...  0.047544  0.048350
...                                ...       ...  ...       ...       ...
control   763_G32   comp 777  0.028903  0.028582  ... -0.004821 -0.003214
          798_AIT3  comp 777  0.022708  0.023809  ...  0.050847  0.070146
          798_G27   comp 777  0.028284  0.034127  ...  0.059824  0.067111
          798_G84   comp 777  0.030418  0.033418  ... -0.005165 -0.009024
          742_G102  comp 777  0.045574  0.049681  ...  0.072403  0.058007

                                   153       154       155       156  \
label     electrode key  sid
aggregate 763_G34   comp 777  0.000186 -0.004286  0.001231  0.005807
          717_LGB71 comp 777  0.096463  0.102267  0.105400  0.107712
          798_G87   comp 777  0.065905  0.062773  0.061782  0.068493
          742_G54   comp 777 -0.048747 -0.059256 -0.066782 -0.071071
          717_LGA32 comp 777  0.055694  0.056053  0.051347  0.050775
...                                ...       ...       ...       ...
control   763_G32   comp 777 -0.004069 -0.009205 -0.007552  0.000578
          798_AIT3  comp 777  0.072439  0.072654  0.071991  0.070867
          798_G27   comp 777  0.075342  0.072962  0.065755  0.063098
          798_G84   comp 777 -0.015009 -0.020522 -0.026239 -0.028400
          742_G102  comp 777  0.042996  0.032677  0.019535  0.007248

                                   157       158       159       160
label     electrode key  sid
aggregate 763_G34   comp 777 -0.001943  0.001051  0.005612  0.006243
          717_LGB71 comp 777  0.106672  0.106192  0.110858  0.115821
          798_G87   comp 777  0.071924  0.070144  0.068306  0.071155
          742_G54   comp 777 -0.068355 -0.059137 -0.050282 -0.043343
          717_LGA32 comp 777  0.049194  0.048995  0.048805  0.049521
...                                ...       ...       ...       ...
control   763_G32   comp 777  0.009645  0.011990  0.014031  0.010608
          798_AIT3  comp 777  0.070128  0.064983  0.060485  0.065601
          798_G27   comp 777  0.067298  0.070768  0.070767  0.069422
          798_G84   comp 777 -0.025490 -0.020874 -0.026187 -0.029004
          742_G102  comp 777  0.001117 -0.001237 -0.001979 -0.004678

[320 rows x 161 columns]

### Encoding Plot

In [ ]:
colors = ["red","blue"]
figsize = (10,5)

fig, ax = plt.subplots(figsize=figsize)
for color, (map_key, subdf) in zip(colors, df.groupby(["label"], axis=0)):
    vals = subdf.mean(axis=0)
    err = subdf.sem(axis=0)
    label = map_key
    ax.fill_between(
        args.lags_show,
        vals - err,
        vals + err,
        alpha=0.2,
        color=color,
    )
    ax.plot(
        args.lags_show,
        vals,
        label=f"{label} ({len(subdf)})",
        color=color,
        ls="-",
    )
ax.axhline(0, ls="dashed", alpha=0.3, c="k")
ax.axvline(0, ls="dashed", alpha=0.3, c="k")
ax.legend(loc="upper right", frameon=False)
ax.set(xlabel="Lag (s)", ylabel="Correlation (r)", title="Global average")
pdf = PdfPages("../aggregate.pdf")
pdf.savefig(fig)
plt.close()
# plt.savefig("../aggregate.jpeg")

In [ ]:
for (electrode, sid), subdf in df.groupby(["electrode", "sid"], axis=0):
    fig, ax = plt.subplots(figsize=figsize)
    for (label, _, _, _), values in subdf.iterrows():
        if label == "aggregate":
            color = "red"
        else:
            color = "blue"
        ax.plot(
            args.lags_show,
            values,
            label=label,
            color=color,
            ls="-",
        )
    ax.axhline(0, ls="dashed", alpha=0.3, c="k")
    ax.axvline(0, ls="dashed", alpha=0.3, c="k")
    ax.set_ylim(-0.1,0.5)
    ax.legend(loc="upper left", frameon=False)
    ax.set(
        xlabel="Lag (s)",
        ylabel="Correlation (r)",
        title=f"{sid} {electrode}",
    )
    imname = get_elecbrain(electrode)
    if os.path.isfile(imname):
        arr_image = plt.imread(imname, format="png")
        fig.figimage(
            arr_image,
            fig.bbox.xmax - arr_image.shape[1],
            fig.bbox.ymax - arr_image.shape[0],
            zorder=5,
        )
    pdf.savefig(fig)
    plt.close()
pdf.close()

### Add max and area

In [4]:
df2 = df.copy()
df2["max"] = df2.loc[:,(np.arange(0,161))].max(axis=1)
df2.reset_index(drop=False, inplace=True)

# area_df = pd.read_csv("../data/plotting/paper-mia/area_electrodes2.csv")
# df2 = df2.merge(area_df, on="electrode",how="left")
# df2
area_df = pd.read_csv("../data/plotting/sig-elecs/podcast-old/elec_masterlist.csv")
area_df["electrode"] = area_df.subject.astype(str) + "_" + area_df.name
df2 = df2.merge(area_df.loc[:,("electrode","NYU_class")], on="electrode",how="left")
df2

,label,electrode,key,sid,0,1,2,3,4,5,...,153,154,155,156,157,158,159,160,max,NYU_class
0,aggregate,763_G34,comp,777,0.000980,0.001336,0.002659,0.010641,0.019509,0.021723,...,0.000186,-0.004286,0.001231,0.005807,-0.001943,0.001051,0.005612,0.006243,0.096225,inferiorparietal
1,aggregate,717_LGB71,comp,777,0.093908,0.094129,0.099867,0.103620,0.111857,0.114492,...,0.096463,0.102267,0.105400,0.107712,0.106672,0.106192,0.110858,0.115821,0.150902,MFG
2,aggregate,798_G87,comp,777,0.088249,0.090593,0.094587,0.100774,0.103142,0.104010,...,0.065905,0.062773,0.061782,0.068493,0.071924,0.070144,0.068306,0.071155,0.167462,IFG
3,aggregate,742_G54,comp,777,-0.010553,-0.009936,-0.011776,-0.011627,-0.009202,-0.011403,...,-0.048747,-0.059256,-0.066782,-0.071071,-0.068355,-0.059137,-0.050282,-0.043343,0.283077,STG
4,aggregate,717_LGA32,comp,777,-0.009871,-0.000145,0.014530,0.021487,0.020341,0.017467,...,0.055694,0.056053,0.051347,0.050775,0.049194,0.048995,0.048805,0.049521,0.083507,supramarginal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,control,763_G32,comp,777,0.025591,0.031791,0.031916,0.027069,0.024121,0.018223,...,-0.004069,-0.009205,-0.007552,0.000578,0.009645,0.011990,0.014031,0.010608,0.204796,postcentral
316,control,798_AIT3,comp,777,0.073384,0.068620,0.059497,0.044098,0.030089,0.027063,...,0.072439,0.072654,0.071991,0.070867,0.070128,0.064983,0.060485,0.065601,0.139725,fusiform
317,control,798_G27,comp,777,0.028355,0.024463,0.020920,0.023100,0.023123,0.017228,...,0.075342,0.072962,0.065755,0.063098,0.067298,0.070768,0.070767,0.069422,0.147257,IFG
318,control,798_G84,comp,777,0.009439,0.014034,0.015819,0.014239,0.014068,0.015365,...,-0.015009,-0.020522,-0.026239,-0.028400,-0.025490,-0.020874,-0.026187,-0.029004,0.248859,IFG
319,control,742_G102,comp,777,0.049758,0.047470,0.046322,0.043966,0.038675,0.033392,...,0.042996,0.032677,0.019535,0.007248,0.001117,-0.001237,-0.001979,-0.004678,0.257938,STG

### Encoding plots for areas

In [ ]:
colors = ["red","blue"]
figsize = (10,5)

area = "AG"
df_area = df2[df2.NYU_class == area]

fig, ax = plt.subplots(figsize=figsize)
for color, (map_key, subdf) in zip(colors, df_area.groupby(["label"], axis=0)):
    vals = subdf.loc[:,(np.arange(0,161))].mean(axis=0)
    err = subdf.loc[:,(np.arange(0,161))].sem(axis=0)
    label = map_key
    ax.fill_between(
        args.lags_show,
        vals - err,
        vals + err,
        alpha=0.2,
        color=color,
    )
    ax.plot(
        args.lags_show,
        vals,
        label=f"{label} ({len(subdf)})",
        color=color,
        ls="-",
    )
ax.axhline(0, ls="dashed", alpha=0.3, c="k")
ax.axvline(0, ls="dashed", alpha=0.3, c="k")
ax.legend(loc="upper right", frameon=False)
ax.set(xlabel="Lag (s)", ylabel="Correlation (r)", title="Global average")
plt.savefig("../AG.jpeg")

### Max Corr

In [ ]:
class Args(argparse.Namespace):
  main_dir = "../data/plotting/brainplot/" # loads coordinate and brain surface files
  project = "podcast"
  sid = [777] # subjects
  keys = ["comp"] # comprehension and/or production
  sig_elec_file = ["../data/plotting/sig-elecs/podcast_160.csv"]
  brain_type = "ave" # average brain
  hemisphere = "both" # only plot left hemisphere
  outfile = "../podcast_%s.png"
  final = False
  final2 = False
  shiny = False

args = Args()

args.color_split = [Colorbar(title="best layer",colorscale="viridis",bar_max=0.4, bar_min=0)]

df_plot = df2.copy()
df_plot["effect"] = df_plot["max"]
df_plot["subject"] = df_plot.electrode.str.split("_", n=1, expand=True)[0]
for model, subdf in df_plot.groupby("label", axis=0):
    subdf_plot = subdf.loc[:, ("subject", "electrode", "effect")]
    print(model, subdf_plot.effect.mean())
    fig = make_brainmap(args, subdf_plot, args.outfile % model) # plot png

### Max Corr Diff

In [20]:
class Args(argparse.Namespace):
  main_dir = "../data/plotting/brainplot/" # loads coordinate and brain surface files
  project = "podcast"
  sid = [777] # subjects
  keys = ["comp"] # comprehension and/or production
  sig_elec_file = ["../data/plotting/sig-elecs/podcast_160.csv"]
  brain_type = "ave" # average brain
  hemisphere = "both" # only plot left hemisphere
  outfile = "../podcast-diff-%s-area.png"
  final = False
  final2 = False
  shiny = False

args = Args()

# Colorsplit
neg_bar = Colorbar(title=f"Δ % corr neg",colorscale=[[0, "rgb(255,0,0)"],[1, "rgb(255,248,240)"]],bar_min=-0.1,bar_max=0)
pos_bar = Colorbar(title=f"Δ % corr pos",colorscale=[[0, "rgb(240,248,255)"], [1, "rgb(0,0,255)"]],bar_min=0,bar_max=0.1)
args.color_split = [neg_bar,0,pos_bar]

df_plot = df2.copy()
lags_plot = np.arange(-2,2.001,0.025)
# lags_plot = np.arange(-1,1.001,0.025)
df_plot["curve_area"] = np.trapz(df_plot.loc[:,(np.arange(0,161))], x=lags_plot, axis=1)
# df_plot["curve_area"] = np.trapz(df_plot.loc[:,(np.arange(40,121))], x=lags_plot, axis=1)
df_base = df_plot.loc[df_plot["label"] == "control",("electrode","max","curve_area")].copy()
df_plot = df_plot.merge(df_base,left_on="electrode",right_on="electrode",how="outer")
# df_plot["effect"] = (df_plot["max_x"] - df_plot["max_y"]) / df_plot[["max_x", "max_y"]].max(axis=1)
# df_plot["effect"] = df_plot["max_x"] / df_plot["max_y"] * 100 - 100
df_plot["effect"] = df_plot["curve_area_x"] - df_plot["curve_area_y"]
# df_plot["effect"] = df_plot["max_x"] - df_plot["max_y"]
df_plot["subject"] = df_plot.electrode.str.split("_", n=1, expand=True)[0]
for model, subdf in df_plot.groupby("label", axis=0):
  if model == "control":
    continue
  subdf_plot = subdf.loc[:, ("subject", "electrode", "effect")]
  print(model, subdf_plot.effect.describe())
  fig = make_brainmap(args, subdf_plot, args.outfile % model) # plot png

aggregate count    160.000000
mean      -0.010093
std        0.032613
min       -0.166348
25%       -0.024789
50%       -0.005592
75%        0.009775
max        0.068373
Name: effect, dtype: float64
Number of electrodes for encoding: 160
Number of electrodes for plotting: 160
Plot Hemisphere
Plot Hemisphere
Plotting 97 Electrodes with ave coordinates
Plotting 63 Electrodes with ave coordinates
Writing to ../podcast-diff-aggregate-area.png